globals = {
	"get_mod",

	"local_require", "class", "ripairs",
	"BuffUI", "EquipmentUI", "AbilityUI", "UnitFrameUI", "MissionObjectiveUI",
	"TutorialUI", "math", "UnitFramesHandler", "table", "UIWidget",
	"UIRenderer", "CrosshairUI", "ScriptUnit", "BossHealthUI", "Colors", "UIWidgets",
	"fassert", "HeroView", "Managers", "UIResolutionScale", "UIResolution",
	"WeaponProperties", "WeaponTraits", "WeaponSkins", "ItemMasterList",
	"SPProfiles", "Localize", "ItemHelper", "UIUtils", "HeroWindowLoadoutInventory",
	"BackendUtils", "OutlineSystem", "script_data", "IngameUI", "GameSession",
	"InventorySettings", "UISceneGraph", "RESOLUTION_LOOKUP", "GamePadEquipmentUI",
	"UISettings", "RewardPopupUI", "EndViewStateChest", "EndViewStateSummary",
	"UIAnimator", "BuffFunctionTemplates", "MOOD_BLACKBOARD", "StateInGameRunning",
	"BuffExtension", "Unit", "Pacing", "RecycleSettings", "CurrentPacing",
	"HordeSpawner", "SpawnerSystem", "ConflictUtils", "CurrentHordeSettings",
	"DoorSystem", "TerrorEventMixer", "ConflictDirector", "Breeds", "AIInterestPointSystem",
	"SpecialsPacing", "CurrentSpecialsSettings", "SpawnZoneBaker", "DamageUtils",
	"CurrentBossSettings", "Application", "HordeSettings", "PlayerHud", "StateLoading",
	"OutlineSettings", "GenericHitReactionExtension", "UnitGibSettings",
	"FrameTable", "NetworkUnit", "CareerSettings", "NetworkLookup", "DialogueSystem",
	"ActionBulletSpray", "ActionShotgun", "ActionHandgunLock", "ActionHandgun",
	"ActionCareerWEWaywatcher", "ActionCareerBWScholar", "ActionCareerDRRanger",
	"ActionCareerWHBountyhunter", "ActionBountyHunterHandgun", "GenericTrailExtension", "PlayerProjectileHuskExtension", "PlayerProjectileUnitExtension",
	"PickupUnitExtension", "AllPickups", "GearUtils", "Light",

	"PriorityBuffUI",
}
