globals = {
	"get_mod",

	"local_require", "class", "ripairs",
	"BuffUI", "EquipmentUI", "AbilityUI", "UnitFrameUI", "MissionObjectiveUI",
	"TutorialUI", "math", "UnitFramesHandler", "table", "UIWidget",
	"UIRenderer", "CrosshairUI", "ScriptUnit", "BossHealthUI", "Colors", "UIWidgets",
	"fassert", "HeroView", "Managers", "UIResolution",
	"WeaponProperties", "WeaponTraits", "WeaponSkins", "ItemMasterList",
	"SPProfiles", "Localize", "ItemHelper", "UIUtils", "HeroWindowLoadoutInventory",
	"BackendUtils", "OutlineSystem", "script_data", "IngameUI", "GameSession",
	"InventorySettings", "UISceneGraph", "RESOLUTION_LOOKUP", "GamePadEquipmentUI",
	"UISettings", "RewardPopupUI", "EndViewStateChest", "EndViewStateSummary",
	"UIAnimator", "BuffFunctionTemplates", "MOOD_BLACKBOARD", "StateInGameRunning",
	"BuffExtension", "Unit", "Pacing", "RecycleSettings", "CurrentPacing",
	"HordeSpawner", "SpawnerSystem", "ConflictUtils", "CurrentHordeSettings",
	"DoorSystem", "TerrorEventMixer", "ConflictDirector", "Breeds", "AIInterestPointSystem",
	"SpecialsPacing", "CurrentSpecialsSettings", "SpawnZoneBaker", "DamageUtils",
	"CurrentBossSettings", "Application", "HordeSettings", "PlayerHud", "StateLoading",
	"OutlineSettings", "GenericHitReactionExtension", "UnitGibSettings",
	"FrameTable", "NetworkUnit", "CareerSettings", "NetworkLookup", "DialogueSystem",
	"ActionBulletSpray", "ActionShotgun", "ActionHandgunLock", "ActionHandgun",
	"ActionCareerWEWaywatcher", "ActionCareerBWScholar", "ActionCareerDRRanger",
	"ActionCareerWHBountyhunter", "ActionBountyHunterHandgun", "GenericTrailExtension",
	"PlayerProjectileHuskExtension", "PlayerProjectileUnitExtension", "SpawnManager",
	"PickupUnitExtension", "AllPickups", "GearUtils", "Light", "GameModeManager",
	"RespawnHandler", "AreaIndicatorUI", "AIGroupTemplates", "DifficultyManager", "DifficultySettings", "LevelEndView", "EndScreenUI", "Color", "Vector2", "Vector3", "Gui", "World", "WwiseWorld",
	"DefaultDifficulties", "UIGetFontHeight", "HeroViewStateLoot",
	"PlayerUnitFirstPerson", "PlayerUnitMovementSettings", "BuffTemplates",
	"GenericAmmoUserExtension", "PlayerUnitHealthExtension",
	"MutatorHandler", "MutatorTemplates", "AttachmentUtils",
	"SubtitleGui", "OverchargeBarUI", "UILayer",
	"PositiveReinforcementUI", "UIAnimation",
	"Development", "PlayerUnitOverchargeExtension",
	"DamageDataIndex", "StateIngame", "FatigueUI",
	"StartGameWindowMission", "StartGameWindowMutator",
	"StartGameWindowTwitchLogin", "StartGameWindowAdventure",
	"PickupSystem", "ChatGui", "WaitForRescueUI",
	"TwitchVoteUI", "TwitchIconView", "EAC",
	"AiUtils", "IngameHud", "Material",
	"callback", "cjson", "UPDATE_RESOLUTION_LOOKUP",
	"WeaponSystem", "BLACKBOARDS", "Clipboard",
	"RconUI", "Keyboard", "Utf8",
	"setfenv", "loadstring", 
	"GenericHealthExtension", "RatOgreHealthExtension",
	"PhysicsWorld", "Actor", "POSITION_LOOKUP",
	"Quaternion", "LocomotionUtils", "GwNavQueries",
	"Vector3Box", "QuaternionBox",
	"BTCorruptorGrabAction", "BTPackMasterAttackAction",
	"GameModeAdventure", "BTConditions", "UITooltipPasses",
	"MenuWorldPreviewer", "SimpleHuskInventoryExtension",
	"SimpleInventoryExtension", "PackageManager",
	"LobbyAux", "AreaDamageSystem", "ExplosionTemplates",
	"ItemGridUI", "Matrix4x4Box", "LineObject",
	"EnemyRecycler", "ShadingEnvironment",
	"MoodHandler", "BTEnterHooks", "BTSpawnAllies",
	"Utility", "GenericStatusExtension",
	"StatusSystem", "BreedActions",
	"BTSkulkIdleAction", "BTStaggerAction",
	"BTNinjaApproachAction", "BTNinjaApproachAction",
	"BTTargetPouncedAction", "BTCrazyJumpAction",
	"BTSkulkAroundAction",
	"BTRatlingGunnerShootAction", "BTRatlingGunnerWindUpAction",
	"PerceptionUtils", "BTSuicideRunAction",
	"EnemyPackageLoader", "EnemyPackageLoaderSettings",
	"CareerExtension", "StartGameWindowMissionSelection",
	"StatisticsUtil", "BTTransformAction", "BTSpawningAction",
	"UtilityConsiderations", "BTChaosSorcererPlagueSkulkAction",
	"GameNetworkManager", "LevelHelper",
	"LoadingView", "HeroViewStateAchievements",
	"AchievementManager", "AchievementTemplates",
	"UIAtlasHelper", "BuffPresentationUI",
	"AdventureSpawning", "WeaveTraits",
	"AIGroupSystem", "UIPasses",
	"PingSystem",

	"PriorityBuffUI",
}
ignore = {"611", "631"}
