local mod = get_mod("SpawnTweaks") -- luacheck: ignore get_mod

local mod_data = {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
}

mod.SETTING_NAMES = {
	HORDE_SIZE = "horde_size",
	EVENT_HORDE_SIZE = "event_horde_size",
	DISABLE_AMBIENTS = "disable_ambients",
	DISABLE_PATROLS = "disable_patrols",
	DISABLE_ROAMING_PATROLS = "disable_roaming_patrols",
	DISABLE_TIMED_SPECIALS = "disable_timed_specials",
	DISABLE_FIXED_EVENT_SPECIALS = "fixed_event_specials",
	DISABLE_BOSSES = "disable_bosses",
	NO_BOSS_DOOR = "no_boss_door",
	SPAWN_COOLDOWN_MIN = "spawn_cooldown_min",
	SPAWN_COOLDOWN_MAX = "spawn_cooldown_max",
	SAFE_ZONE_DELAY_MIN = "safe_zone_delay_min",
	SAFE_ZONE_DELAY_MAX = "safe_zone_delay_max",
	NO_EMPTY_EVENTS = "no_empty_events",
	MAX_SPECIALS = "max_specials",
	MAX_SAME_SPECIALS = "max_same_specials",
	DOUBLE_BOSSES = "double_bosses",
	THREAT_MULTIPLIER = "threat_multiplier",
	MAX_GRUNTS = "max_grunts",
	HORDE_GRUNT_LIMIT = "horde_grunt_limit",
	HORDE_FREQUENCY_MIN = "horde_frequency_min",
	HORDE_FREQUENCY_MAX = "horde_frequency_max",
	AMBIENTS_MULTIPLIER = "ambients_multiplier",
	MORE_AMBIENT_ELITES = "more_ambient_elites",
	NO_TROLL = "no_troll",
}

mod_data.options_widgets = {
	{
		["setting_name"] = mod.SETTING_NAMES.HORDE_SIZE,
		["widget_type"] = "numeric",
		["text"] = mod:localize("horde_size"),
		["tooltip"] = mod:localize("horde_size_tooltip"),
		["range"] = {0, 300},
		["unit_text"] = "%",
		["default_value"] = 100,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.EVENT_HORDE_SIZE,
		["widget_type"] = "numeric",
		["text"] = mod:localize("event_horde_size"),
		["tooltip"] = mod:localize("event_horde_size_tooltip"),
		["range"] = {0, 300},
		["unit_text"] = "%",
		["default_value"] = 100,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_AMBIENTS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_ambients"),
		["tooltip"] = mod:localize("disable_ambients_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_PATROLS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_patrols"),
		["tooltip"] = mod:localize("disable_patrols_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_ROAMING_PATROLS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_roaming_patrols"),
		["tooltip"] = mod:localize("disable_roaming_patrols_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_TIMED_SPECIALS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_timed_specials"),
		["tooltip"] = mod:localize("disable_timed_specials_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_FIXED_EVENT_SPECIALS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_fixed_event_specials"),
		["tooltip"] = mod:localize("disable_fixed_event_specials_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DISABLE_BOSSES,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("disable_bosses"),
		["tooltip"] = mod:localize("disable_bosses_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.DOUBLE_BOSSES,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("double_bosses"),
		["tooltip"] = mod:localize("double_bosses_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.NO_TROLL,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("no_troll"),
		["tooltip"] = mod:localize("no_troll_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.NO_BOSS_DOOR,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("no_boss_door"),
		["tooltip"] = mod:localize("no_boss_door_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.SPAWN_COOLDOWN_MIN,
		["widget_type"] = "numeric",
		["text"] = mod:localize("spawn_cooldown_min"),
		["tooltip"] = mod:localize("spawn_cooldown_min_tooltip"),
		["range"] = {0, 150},
		["unit_text"] = " sec",
		["default_value"] = 50,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.SPAWN_COOLDOWN_MAX,
		["widget_type"] = "numeric",
		["text"] = mod:localize("spawn_cooldown_max"),
		["tooltip"] = mod:localize("spawn_cooldown_max_tooltip"),
		["range"] = {0, 150},
		["unit_text"] = " sec",
		["default_value"] = 90,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.SAFE_ZONE_DELAY_MIN,
		["widget_type"] = "numeric",
		["text"] = mod:localize("safe_zone_delay_min"),
		["tooltip"] = mod:localize("safe_zone_delay_min_tooltip"),
		["range"] = {0, 100},
		["unit_text"] = " sec",
		["default_value"] = 30,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.SAFE_ZONE_DELAY_MAX,
		["widget_type"] = "numeric",
		["text"] = mod:localize("safe_zone_delay_max"),
		["tooltip"] = mod:localize("safe_zone_delay_max_tooltip"),
		["range"] = {0, 100},
		["unit_text"] = " sec",
		["default_value"] = 60,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.NO_EMPTY_EVENTS,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("no_empty_events"),
		["tooltip"] = mod:localize("no_empty_events_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.MAX_SPECIALS,
		["widget_type"] = "numeric",
		["text"] = mod:localize("max_specials"),
		["tooltip"] = mod:localize("max_specials_tooltip"),
		["range"] = {0, 25},
		["default_value"] = 4,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.MAX_SAME_SPECIALS,
		["widget_type"] = "numeric",
		["text"] = mod:localize("max_same_specials"),
		["tooltip"] = mod:localize("max_same_specials_tooltip"),
		["range"] = {0, 25},
		["default_value"] = 2,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.HORDE_FREQUENCY_MIN,
		["widget_type"] = "numeric",
		["text"] = mod:localize("horde_frequency_min"),
		["tooltip"] = mod:localize("horde_frequency_min_tooltip"),
		["range"] = {5, 150},
		["unit_text"] = " sec",
		["default_value"] = 50,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.HORDE_FREQUENCY_MAX,
		["widget_type"] = "numeric",
		["text"] = mod:localize("horde_frequency_max"),
		["tooltip"] = mod:localize("horde_frequency_max_tooltip"),
		["range"] = {5, 200},
		["unit_text"] = " sec",
		["default_value"] = 100,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.THREAT_MULTIPLIER,
		["widget_type"] = "numeric",
		["text"] = mod:localize("threat_multiplier"),
		["tooltip"] = mod:localize("threat_multiplier_tooltip"),
		["range"] = {0.1, 1},
		["decimals_number"] = 1,
		["default_value"] = 1,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.MAX_GRUNTS,
		["widget_type"] = "numeric",
		["text"] = mod:localize("max_grunts"),
		["tooltip"] = mod:localize("max_grunts_tooltip"),
		["range"] = {10, 360},
		["default_value"] = 90,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.HORDE_GRUNT_LIMIT,
		["widget_type"] = "numeric",
		["text"] = mod:localize("horde_grunt_limit"),
		["tooltip"] = mod:localize("horde_grunt_limit_tooltip"),
		["range"] = {10, 240},
		["default_value"] = 60,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.MORE_AMBIENT_ELITES,
		["widget_type"] = "checkbox",
		["text"] = mod:localize("more_ambient_elites"),
		["tooltip"] = mod:localize("more_ambient_elites_tooltip"),
		["default_value"] = false,
	},
	{
		["setting_name"] = mod.SETTING_NAMES.AMBIENTS_MULTIPLIER,
		["widget_type"] = "numeric",
		["text"] = mod:localize("ambients_multiplier"),
		["tooltip"] = mod:localize("ambients_multiplier_tooltip"),
		["range"] = {10, 1500},
		["unit_text"] = "%",
		["default_value"] = 100,
	},
}

return mod_data